---
title: "TB Vaccination"
output: 
  - pdf_document
  - html_notebook
---

PDF Version available [here](http://rwhite.no/tb_vaccination/tb_vaccination.pdf).

```{r, message=FALSE, warning=FALSE}
library(data.table)
library(pomp)
library(ggplot2)
library(rstan)

rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())

#everyone enters on jan 1
#results are for dec 31
newPeople <- data.table(id=1:100,year=2000,age=1,timeNotVax=0,timeWithVax=0,vaccinated=0,ltbi=0,atbi=0)

pomp::bake("data/peopleNoVax.RDS",{
  set.seed(4)
  peopleNoVax <- vector("list",length=17)
  peopleNoVax[[1]] <- newPeople[1,][-1,]
  for(i in 1:17){
    # NO VACCINATIONS
    if(i!=1) peopleNoVax[[i]] <- copy(peopleNoVax[[i-1]])
    peopleNoVax[[i]][,age:=age+1]
    peopleNoVax[[i]] <- rbind(peopleNoVax[[i]],newPeople)
    peopleNoVax[[i]][,year:=2000+i]
    
    N <- nrow(peopleNoVax[[i]])
    peopleNoVax[[i]][sample(1:N,size=round(N*0.050)),ltbi:=1]
    peopleNoVax[[i]][,timeNotVax:=timeNotVax+1]
    
    Nltbi <- sum(peopleNoVax[[i]]$ltbi)
    peopleNoVax[[i]][sample(which(peopleNoVax[[i]]$ltbi==1),size=round(Nltbi*0.05)),atbi:=1]
  }
  peopleNoVax
}) -> peopleNoVax

pomp::bake("data/peopleWithVax.RDS",{
  set.seed(4)
  peopleWithVax <- vector("list",length=17)
  peopleWithVax[[1]] <- newPeople[1,][-1,]
  for(i in 1:17){
    # WITH VACCINATIONS, BUT STOPPING THEM AFTERWARDS
    if(i!=1) peopleWithVax[[i]] <- copy(peopleWithVax[[i-1]])
    peopleWithVax[[i]][,age:=age+1]
    peopleWithVax[[i]] <- rbind(peopleWithVax[[i]],newPeople)
    peopleWithVax[[i]][,year:=2000+i]
    N <- nrow(peopleWithVax[[i]])
    if(i>=10){
      peopleWithVax[[i]][sample(1:N,size=round(N*0.050)),ltbi:=1]
      peopleWithVax[[i]][,timeNotVax:=timeNotVax+1]
    } else {
      peopleWithVax[[i]][sample(1:N,size=round(N*0.050)),ltbi:=1]
      peopleWithVax[[i]][,timeWithVax:=timeWithVax+1]
    }
    
    Nltbi <- sum(peopleWithVax[[i]]$ltbi)
    peopleWithVax[[i]][sample(which(peopleWithVax[[i]]$ltbi==1),size=round(Nltbi*0.05)),atbi:=1]
  }
  peopleWithVax
}) -> peopleWithVax
```

Lets try an easy model, detecting LTBI in unvaccinated people.

```{r}
stanData=peopleNoVax[[17]]
data = list(N=nrow(stanData),
            y=stanData$ltbi,
            timeNotVax=stanData$timeNotVax)

stan_code = "
data {
  int<lower=0> N;
  vector[N] timeNotVax;
  int y[N];
}
parameters {
  real<lower=0,upper=0.5> thetaNotVax;
}
model {
  thetaNotVax ~ beta(0.05, 1);
  
  for (n in 1:N) 
    y[n] ~ bernoulli(1-((1-thetaNotVax)^timeNotVax[n]));
}
"
pomp::bake("results/noVax.RDS",{
stan(model_code=stan_code,
            model_name="noVax",
            data=data,
            iter=2000, chains=1, init=0)
}) -> fit
summary(fit)$summary
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Cmd+Option+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Cmd+Shift+K* to preview the HTML file).
